In [3]:
# Python list
import numpy as np
python_list = [1, 2, 3, 4, 5]

# What happens with math on lists?
print(python_list * 2)       # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]  ← NOT what you want!
print(python_list + [10])    # [1, 2, 3, 4, 5, 10]              ← just appends

# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

print(numpy_array * 2)       # [ 2  4  6  8 10] ← multiplies every element
print(numpy_array + 10)      # [11 12 13 14 15] ← adds 10 to every element

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 10]
[ 2  4  6  8 10]
[11 12 13 14 15]


In [4]:
# --- 1D Array (from a flat list) ---
temperatures = [72, 75, 68, 80, 77]
temp_array = np.array(temperatures)
print("1D Array:", temp_array)

# --- 2D Array (from a nested list) ---
matrix_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrix_array = np.array(matrix_list)
print("2D Array:\n", matrix_array)

# --- Float Array ---
prices = [9.99, 4.50, 12.75, 3.00]
price_array = np.array(prices)
print("Float Array:", price_array)

1D Array: [72 75 68 80 77]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Float Array: [ 9.99  4.5  12.75  3.  ]


In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Array:\n", arr)
print("Shape:     ", arr.shape)      # (2, 3) → 2 rows, 3 columns
print("Data type: ", arr.dtype)      # int64
print("Dimensions:", arr.ndim)       # 2
print("Total items:", arr.size)      # 6

Array:
 [[10 20 30]
 [40 50 60]]
Shape:      (2, 3)
Data type:  int64
Dimensions: 2
Total items: 6


In [6]:
scores = np.array([85, 90, 78, 92, 88])

# Arithmetic — applied to every element
print(scores + 5)          # [90 95 83 97 93]  ← add 5 to all
print(scores * 2)          # [170 180 156 184 176]
print(scores / 100)        # [0.85 0.90 0.78 0.92 0.88]

# Summary statistics
print("Mean:  ", scores.mean())    # 86.6
print("Max:   ", scores.max())     # 92
print("Min:   ", scores.min())     # 78
print("Sum:   ", scores.sum())     # 433

# Operations between two arrays
quiz1 = np.array([10, 8, 9])
quiz2 = np.array([7, 9, 6])
total = quiz1 + quiz2
print("Combined scores:", total)   # [17 17 15]

[90 95 83 97 93]
[170 180 156 184 176]
[0.85 0.9  0.78 0.92 0.88]
Mean:   86.6
Max:    92
Min:    78
Sum:    433
Combined scores: [17 17 15]


In [7]:
py_list  = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])

# Addition
print(py_list  + [10, 20, 30, 40, 50])   # [1,2,3,4,5,10,20,30,40,50] ← concatenates
print(np_array + np.array([10,20,30,40,50]))  # [11 22 33 44 55] ← element-wise

# Scalar math
# py_list + 10  → TypeError!
print(np_array + 10)   # [11 12 13 14 15] ← works perfectly

# Mixed types — lists allow it, arrays don't (homogeneous)
mixed_list  = [1, "two", 3.0]          # totally fine
mixed_array = np.array([1, "two", 3.0])
print(mixed_array.dtype)               # <U21 — everything forced to string!

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]
[11 12 13 14 15]
<U32
